// Vampl/client/messanger/src/pages/AuthPage.tsx
import { Ref, useCallback, useEffect, useRef, useState } from "react";
import { Helmet } from "react-helmet";
import { AuthInputs, SignData, Store } from "../types/global";
import { useSelector } from "react-redux";
import useSwitcher from "../components/functions/useSwitcher";
import serv from "../components/functions/interceptors";
import parsePassword from "../components/functions/parsePassword";
import auth from "../components/functions/sign";
import triggerEffect from "../components/functions/bubbleEffect";
import '../components/styles/auth.css';

const AuthPage = () => {
  const ip = useSelector((state:Store) => state.user.ip);
  const [phoneCodes,setPhoneCodes] = useState<any>([]);
  const phoneInput:Ref<any | null> = useRef(null);
  const [phoneCode,setPhoneCode] = useState('+1');
  const [country,setCountry] = useState('United States');
  const codeSelector:Ref<HTMLDivElement | null> = useRef(null);
  const [codeOptions,setCodeOptions] = useState<Boolean>(false);
  const [strokes,setStrokes] = useState<number>(11);
  const [currentWindow,setCurrentWindow] = useState<AuthInputs>('phone');
  const [inputError,setInputError] = useState<AuthInputs | ''>('');
  const [register,setRegister] = useState<Boolean>(false);
  const inputData:SignData | any = {};  
  const [userInput,setInput] = useState<string>("");
  const switcher = useSwitcher(setCodeOptions);

  const changeCode = (code:string) => {
    if(code) {
      setPhoneCode(code);
    }

    phoneInput.current.innerText = `${code ?? '+1'}`;
    const strokes = 12 - (phoneInput.current.innerText.length - 1);
    setStrokes(strokes);
    changeStrokes(strokes);
  }

  const changeStrokes = (currentStrokes:number) => {
    console.log('strokes:',currentStrokes);
    const newSpaces = "-".repeat(currentStrokes)
    .split('').map((stroke,i,arr) => {
      if(i % Math.floor(arr.length / 3) === 0) {
        return stroke + " ";
      }

      return stroke;
    }).join('');

    phoneInput.current.setAttribute('data-left-pattern',newSpaces);
  }

  const saveCursorPosition = (el:any) => {
  const selection:any = window.getSelection();
  if (!selection.rangeCount) return null; // Если курсора нет, выходим
  
  const range = selection.getRangeAt(0); // Берём текущий диапазон выделения
  const preCaretRange = range.cloneRange(); // Копируем его
  
  preCaretRange.selectNodeContents(el); // Берём весь контент
  preCaretRange.setEnd(range.endContainer, range.endOffset); // Ставим конец в текущую позицию

  const cursorPosition = preCaretRange.toString().length; // Считаем длину текста до курсора
  return cursorPosition;
};

const restoreCursorPosition = (el:any, cursorPosition:any) => {
  const selection:any = window.getSelection();
  selection.removeAllRanges(); // Убираем старые выделения
  
  const range = document.createRange();
  let charCount = 0;
  
  const findPosition = (node:any) => {
    if (node.nodeType === Node.TEXT_NODE) {
      const nextCharCount = charCount + node.length;
      
      if (cursorPosition <= nextCharCount) {
        range.setStart(node, cursorPosition - charCount);
        range.setEnd(node, cursorPosition - charCount);
        return true;
      }
      
      charCount = nextCharCount;
    } else {
      for (let i = 0; i < node.childNodes.length; i++) {
        if (findPosition(node.childNodes[i])) return true;
      }
    }
    return false;
  };

  findPosition(el);
  selection.addRange(range); // Восстанавливаем курсор
};

  const PhoneValidation = () => {
    const cursorPosition = saveCursorPosition(phoneInput.current);
    const currentContent = phoneInput.current.innerText.replace(/\s/g,"");
    console.log('current:',currentContent.length);
    const newStrokes = 12 - (phoneInput.current.innerText.length - 1);
    setStrokes(newStrokes);

    if(currentContent.length > 1 && inputError === 'phone') {
      setInputError('');
    }
    
    if(!/^[0-9\+]*$/.test(currentContent)) {
       phoneInput.current.innerText = currentContent.slice(0,-1);
       restoreCursorPosition(phoneInput.current,cursorPosition - 1);
       return;
    }

    if(strokes < 0) {
      phoneInput.current.innerText = currentContent.slice(0,-1);
      restoreCursorPosition(phoneInput.current,cursorPosition - 1);
      phoneInput.current.blur();
      return;
    }

    changeStrokes(newStrokes);
  }

  useEffect(() => {
     if(currentWindow === 'phone') {
       changeStrokes(strokes);
     }
  },[currentWindow]); 

  const WriteInput = (event:any) => {
    setInput(event.target.value);
    if(inputError) {
      setInputError('');
    }
  }

  const signActions = async () => {
    console.log('window:',currentWindow);
     switch(currentWindow) {
        case 'phone':
         const currentPhone = phoneInput.current.innerText;
         if(currentPhone.length < 12) {
            setInputError('phone');
            break;
         }

         const res:any = await serv.get(`/user/phone/${currentPhone}`);

         inputData['phone'] = currentPhone;
         console.log('register?:',res);
         setRegister(res.register);

         if(!res.register) {
            setCurrentWindow('name');
            break;
         } 
         
         setCurrentWindow('password');
         break;
        case 'name':
         inputData['name'] = userInput;
         setInput('');
         setCurrentWindow('password');
          break;
        case 'password':
        console.log('simple:',userInput);
        if(!parsePassword(userInput)) {
          setInputError('password');
          setInput('')
          break;
        }
        inputData['password'] = userInput;
        inputData['ip'] = ip;
        setInput('');
        const authReq:any = await auth(register,inputData,ip,inputError);
        console.log("AUTH:",authReq);
        if((await authReq).window === 'password') {
          setCurrentWindow('password');
        } else {
          window.location.href = "/";
        }
        break;
     }
  }

  const fastEnter = (event:KeyboardEvent) => {
    if(event.key === 'Enter') {
      event.preventDefault();
      signActions();
    }
  }

  const changeValue = (country:string,code:string) => {
     if(country) {
        setCountry(country);
     }

     changeCode(code);
  }

  const checkPaste = (event:ClipboardEvent | any) => {
    const pasteData = event.clipboardData.getData('text');
    event.preventDefault();
    if(!/[A-Z,a-z]/g.test(pasteData)) {
      phoneInput.current.innerText += pasteData;
      PhoneValidation();
    }
  }

  useEffect(() => {
    const setupPage = async () => {
      const fetchedCodes:any = await fetch("http://localhost:3000/getData/phoneCodes")
      .then(d => d.json());
       setPhoneCodes((_:any) => {
        const elements = [];

        for(const [index,code] of Object.entries(fetchedCodes)) {
          elements.push(
            <div onClick={() => changeValue(index,code as any)} className="code-option" key={`phoneCode-${index}`}>
            <p>{index as any}</p>
            <p className="code" >{code as any}</p>
            </div>
          )
        }
         
        return elements;
       });
  
      if(phoneInput.current && codeSelector.current) {
        phoneInput.current.addEventListener('input',PhoneValidation);
        phoneInput.current.addEventListener('paste',checkPaste);
        codeSelector.current.addEventListener('blur',() => {
          setCodeOptions(false);
        });
        changeCode(phoneCode);
      }
    } 

    setupPage();

    document.addEventListener('keydown',fastEnter);

    return () => document.removeEventListener('keydown',fastEnter);

  },[]);

    return (
      <>
        <Helmet>
            <title>Join to us</title>
        </Helmet>
        <section className="auth-page">
          <div className="container auth-list-container">
              <ul className="auth-list">
               { currentWindow === 'phone' &&
                <li className="auth-window">
                  <div tabIndex={0} onClick={switcher} className="code-selector" style={{pointerEvents:codeOptions ? 'none' : 'all'}} ref={codeSelector}   id="code-selector">
                   {country}
                   <svg className={`default-svg list-arrow ${codeOptions &&'list-arrow-active'}`} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                     <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
                     <g id="SVGRepo_tracerCarrier" strokeLinecap="round" strokeLinejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M12 4L6 10M12 4L18 10M12 4L12 14.5M12 20V17.5"  strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path></g>
                   </svg>
                      { codeOptions && 
                          <div className="code-options container flex-reverse">
                            {phoneCodes}
                          </div>
                      }
                   </div>
                  <div className="input-container">
                   {inputError !== 'phone' ? 
                   <label className="auth-label">Your Phone Number</label> :
                   <label className="auth-label error-label">Wrong Number</label>}
                   <div className={`${inputError === 'phone' && 'input-error'} auth-input`} ref={phoneInput} dir="auto" contentEditable="true" inputMode="decimal"  data-left-pattern="">
                   </div>
                  </div>
                </li>
               }
               { currentWindow === 'name' &&
                  <li className="auth-window">
                    <div className="input-container">
                     <label className="auth-label">Your Name</label>
                     <input  autoFocus={currentWindow === 'name'}  name="name-input" onInput={WriteInput} className="auth-input" type="text"/>
                    </div>
                  </li>
               }
               { currentWindow === 'password' && 
                <li className="auth-window">
                  <div className="input-container">
                    <label className="auth-label">Your password</label>
                    <input autoFocus={currentWindow === 'password'} className={`auth-input ${inputError === 'password' && 'input-error'}`} onChange={WriteInput} name="pass-input" value={userInput}  type="text" />
                    { inputError === 'password' && 
                      <label className="auth-label error-label">
                        Password must contain:
                        <p className="auth-label error-label">A-Z letter</p>
                        <p className="auth-label error-label">0-9 number</p>
                        <p className="auth-label error-label">minimum 8 symbols</p>
                      </label>
                    }
                    { inputError === 'incorrect' && 
                      <label className="auth-label error-label">Password incorrect for this user</label>
                    }
                  </div>
                </li>

               }
               <button onClick={(event:any) => {
                  signActions();
                  triggerEffect(event);
               }} className="auth-button hidden-container">{ currentWindow === 'password' ? 'Enter' : 'Next' }</button>
             </ul>
          </div>
        </section>
      </>
    )
}

export default AuthPage;

// Vampl/frontend/src/components/AuthPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, type Ref} from 'vue';
import useChangeTitle from '../store/changeTitle';
import { useHead } from '@vueuse/head';
import type { AuthInputs, SignData } from '../types/global';
import useUserData from '../store/userData';
import auth from './functions/sign';
import parsePassword from './functions/parsePassword';
import triggerEffect from './functions/bubbleEffect';
import serv from './functions/interceptors';
import useSwitcher from './functions/useSwitcher';

  const phoneCodes = ref({});
  const phoneInput:Ref<any | null> = ref(null);
  const selectedCode = ref('+1');
  const selectedCountry = ref('United States');
  const codeSelector:Ref<HTMLDivElement | null> = ref(null);
  const codeOptions:Ref<Boolean> = ref(false);
  const currentStrokesLength = ref(11);
  const title = useChangeTitle();
  const currentWindow:Ref<AuthInputs> = ref('phone');
  const inputError:Ref<AuthInputs | ''> = ref('');
  const register:Ref<Boolean> = ref(false);
  const inputData:SignData | any = {};
  const simpleInput = ref("");
  const userData = useUserData();
  const switcher = useSwitcher(codeOptions);

  title.changeTitle('Sign in');
  useHead({
    title:title.currentTitle
  });
  
  const changeCode = (code:string) => {
    if(code) {
      selectedCode.value = code;
    }
    phoneInput.value.innerText = `${selectedCode.value ?? '+1'}`;
    currentStrokesLength.value = 12 - (phoneInput.value.innerText.length - 1);
    changeStrokes();
  }

  const changeStrokes = () => {
    const newSpaces = "-".repeat(currentStrokesLength.value)
    .split('').map((stroke,i,arr) => {
      if(i % Math.floor(arr.length / 3) === 0) {
        return stroke + " ";
      }

      return stroke;
    }).join('');

    phoneInput.value.setAttribute('data-left-pattern',newSpaces);
  }

  const saveCursorPosition = (el:any) => {
  const selection:any = window.getSelection();
  if (!selection.rangeCount) return null; // Если курсора нет, выходим
  
  const range = selection.getRangeAt(0); // Берём текущий диапазон выделения
  const preCaretRange = range.cloneRange(); // Копируем его
  
  preCaretRange.selectNodeContents(el); // Берём весь контент
  preCaretRange.setEnd(range.endContainer, range.endOffset); // Ставим конец в текущую позицию

  const cursorPosition = preCaretRange.toString().length; // Считаем длину текста до курсора
  return cursorPosition;
};

const restoreCursorPosition = (el:any, cursorPosition:any) => {
  const selection:any = window.getSelection();
  selection.removeAllRanges(); // Убираем старые выделения
  
  const range = document.createRange();
  let charCount = 0;
  
  const findPosition = (node:any) => {
    if (node.nodeType === Node.TEXT_NODE) {
      const nextCharCount = charCount + node.length;
      
      if (cursorPosition <= nextCharCount) {
        range.setStart(node, cursorPosition - charCount);
        range.setEnd(node, cursorPosition - charCount);
        return true;
      }
      
      charCount = nextCharCount;
    } else {
      for (let i = 0; i < node.childNodes.length; i++) {
        if (findPosition(node.childNodes[i])) return true;
      }
    }
    return false;
  };

  findPosition(el);
  selection.addRange(range); // Восстанавливаем курсор
};

  const PhoneValidation = () => {
    const cursorPosition = saveCursorPosition(phoneInput.value);
    const currentContent = phoneInput.value.innerText.replace(/\s/g,"");
    currentStrokesLength.value = 12 - (phoneInput.value.innerText.length - 1);

    if(currentContent.length > 1 && inputError.value === 'phone') {
      inputError.value = "";
    }
    
    if(!/^[0-9\+]*$/.test(currentContent)) {
       phoneInput.value.innerText = currentContent.slice(0,-1);
       restoreCursorPosition(phoneInput.value,cursorPosition - 1);
       return;
    }

    if(currentStrokesLength.value < 0) {
      phoneInput.value.innerText = currentContent.slice(0,-1);
      restoreCursorPosition(phoneInput.value,cursorPosition - 1);
      phoneInput.value.blur();
      return;
    }

    changeStrokes();
  }

  watch(currentWindow,() => {
     if(currentWindow.value === 'phone') {
       changeStrokes();
     }
  }); 

  const WriteInput = (event:any) => {
    simpleInput.value = event.target.value;
    if(inputError.value) {
      inputError.value = "";
    }
  }

  const signActions = async () => {
     switch(currentWindow.value) {
        case 'phone':
         const currentPhone = phoneInput.value.innerText;
         if(currentPhone.length < 12) {
            inputError.value = 'phone';
            break;
         }

         const res:any = await serv.get(`/user/phone/${currentPhone}`);

         inputData['phone'] = currentPhone;
         console.log('register?:',res);
         register.value = res.register;

         if(!res.register) {
            currentWindow.value = 'name';
            break;
         } 
         
         currentWindow.value = 'password';
         break;
        case 'name':
         inputData['name'] = simpleInput.value;
         simpleInput.value = "";
         currentWindow.value = 'password';
          break;
        case 'password':
        console.log('simple:',simpleInput.value);
        if(!parsePassword(simpleInput.value)) {
          inputError.value = 'password';
          simpleInput.value = '';
          break;
        }

        inputData['password'] = simpleInput.value;
        inputData['ip'] = userData.ip;
        simpleInput.value = "";
        const authReq:any = auth(register,inputData,userData.ip,inputError);
        if((await authReq).window === 'password') {
          currentWindow.value = 'password';
        } else {
          window.location.href = "/";
        }
        break;
     }
  }

  const fastEnter = (event:KeyboardEvent) => {
    if(event.key === 'Enter') {
      event.preventDefault();
      signActions();
    }
  }

  const changeValue = (country:string,code:string) => {
     if(selectedCountry.value) {
        selectedCountry.value = country;
     }

     changeCode(code);
  }

  const checkPaste = (event:ClipboardEvent | any) => {
    const pasteData = event.clipboardData.getData('text');
    event.preventDefault();
    if(!/[A-Z,a-z]/g.test(pasteData)) {
      phoneInput.value.innerText += pasteData;
      PhoneValidation();
    }
  }

  onMounted(async () => {
    phoneCodes.value = await fetch("http://localhost:3000/getData/phoneCodes")
    .then(d => d.json());

    if(phoneInput.value) {
      phoneInput.value.addEventListener('input',PhoneValidation);
      phoneInput.value.addEventListener('paste',checkPaste);
      codeSelector.value?.addEventListener('blur',() => {
        if(codeOptions.value) {
          codeOptions.value = false;
        }
      });
      changeCode(selectedCode.value);
    }

    document.addEventListener('keydown',fastEnter);

  });

  onUnmounted(() => {
    if(phoneInput.value && codeSelector.value) {
      document.removeEventListener('keydown',fastEnter);
    }
  });
</script>

<template>
  <section class="auth-page">
    <div class="container auth-list-container">
        <ul class="auth-list">
         <li v-if="currentWindow === 'phone'" class="auth-window">
           <div tabindex="0" @click="switcher" class="code-selector" :style="{pointerEvents:codeOptions ? 'none' : 'all'}" ref="codeSelector"  name="codes" id="code-selector">
            {{ selectedCountry }}
            <svg class="default-svg list-arrow" viewBox="0 0 24 24" :class="{'list-arrow-active':codeOptions}" fill="none" xmlns="http://www.w3.org/2000/svg">
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M12 4L6 10M12 4L18 10M12 4L12 14.5M12 20V17.5"  stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></g>
            </svg>
              <div class="code-options container flex-reverse" v-if="codeOptions">
                <li @click="() => changeValue(index,code)" class="code-option" v-for="(code,index) in phoneCodes" :value="index" :key="`phoneCode-${index}`">
                  <p>{{ index }}</p>
                  <p class="code" >{{ code }}</p>
                </li>
              </div>
            </div>
           <div class="input-container">
            <label v-if="inputError !== 'phone'" class="auth-label" for="phone-input">Your Phone Number</label>
            <label v-else class="auth-label error-label" for="phone-input">Wrong Number</label>
           <div :class="{'input-error':inputError === 'phone'}"  class="auth-input" ref="phoneInput" dir="auto" contenteditable="true" inputmode="decimal" type="tel"  data-left-pattern="">
           </div>
           </div>
         </li>
         <li v-if="currentWindow === 'name'" class="auth-window">
           <div class="input-container">
            <label class="auth-label" for="name-input">Your Name</label>
            <input  :autofocus="currentWindow === 'name'"  name="name-input" @input="WriteInput" class="auth-input"  type="text">
           </div>
         </li>
         <li v-if="currentWindow === 'password'" class="auth-window">
            <div class="input-container">
              <label class="auth-label" for="pass-input">Your password</label>
              <input :class="{'input-error':inputError === 'password'}" :autofocus="currentWindow === 'password'" class="auth-input" @input="WriteInput" name="pass-input"  type="text">
              <label class="auth-label error-label" v-if="inputError === 'password'" for="pass-input">
                Password must contain:
                <p class="auth-label error-label">A-Z letter</p>
                <p class="auth-label error-label">0-9 number</p>
                <p class="auth-label error-label">minimum 8 symbols</p>
              </label>
              <label v-if="inputError === 'incorrect'" class="auth-label error-label" for="pass-input">Password incorrect for this user</label>
            </div>
         </li>
         <button @click="(event:any) => {
            signActions();
            triggerEffect(event);
         }" class="auth-button hidden-container">{{ currentWindow === 'password' ? 'Enter' : 'Next' }}</button>
       </ul>
    </div>
  </section>
</template>

<style scoped>
  .code {
    color:var(--night-color) !important;
  }

  .list-arrow {
    position:absolute;
    right:1%;
    display:flex;
    align-self:center;
  }

  .list-arrow-active {
    transform:rotate(180deg);
  }


  .auth-input {
    position: relative;
    display: flex;
    align-items: center;
    background-color: var(--secondary-color);
    border: .2rem solid var(--light-grey-half);
    border-radius: var(--default-border-radius);
    color:var(--black-default) !important;
    padding-left: .5rem;
    height: 5rem;
    min-width:70%;
  }

  .code-options {
    position: absolute;
    top:103%;
    overflow-y: scroll;
    height:16rem;
    z-index: 1;
    background-color: var(--chat-bg-color);
    backdrop-filter: blur(.5rem);
    border-radius: 20px;
    pointer-events: all !important;
  }

  .auth-container {
    flex-direction: column;
    justify-content: flex-end;
    align-items: flex-start;
    padding-bottom: 10rem;
  }

  .auth-input:focus-within {
    outline: none;
    border-color:var(--night-color);
  }

  .auth-input::after {
    content: attr(data-left-pattern);
    color:var(--light-grey);
  }
  
  .input-error {
    border-color: var(--error-color) !important;
  }

  .auth-label {
    padding-left: .2rem;
    font-size: 1.3rem !important;
    color:var(--light-grey) !important;
  }

  .error-label {
    color:var(--error-color) !important;
  }

  .input-container {
    display: flex;
    flex-direction: column;
    margin: 1rem 0;
  }

  .input-container * {
    margin: .2rem;
  }


  .auth-page {
    position: relative;
    width: 100%;
    height: 100%;
    display: flex;
    background-color: var(--bg-main);
  }

  .auth-page * {
    color: var(--secondary-color);
    font-weight: 500;
    font-size: 1.5rem;
  }


  .auth-list-container {
    justify-content: center;
    align-items: center;
  }

  .auth-list {
    position: relative;
    display: flex;
    flex-direction: column;
    padding: 0;
    margin: 0;
  }

  .auth-window {
    position: relative;
    width: 40rem;
    height: 30rem;
    display: inherit;
    justify-content: center;
    align-items: center;
    flex-direction: column;
  }

  .auth-list > li,button {
    margin: .6rem 0;
  }

  .code-selector {
    position: relative;
    width: 90%;
    height: 6rem;
    display:flex;
    align-items: center;
    background-color: var(--chat-bg-color);
    padding: .5rem;
    outline: none;
    border-color: none;
    border-radius: var(--default-border-radius);
    scrollbar-color:var(--scrollbar-color);
    scrollbar-width:thin;
    cursor: pointer;
  }

  .code-option {
    width: 100%;
    height: 4rem;
    cursor: pointer;
    padding-left: .2rem;
    user-select: none;
    display: flex;
  }

  .code-option > * {
    margin: 0 .5rem;
  }

  .code-option:hover {
    background-color: var(--night-color);
  }

  .code-option:hover .code {
    color:var(--secondary-color) !important;
  }

  .code-option:checked {
    background-color: var(--night-color);
  }

  .code-selector::-webkit-scrollbar-track {
  background: var(--bg-main); 
  border-radius: 4px;
}

  .code-selector::-webkit-scrollbar-thumb {
     background: var(--light-grey);
  }

  .code-selector:focus {
    box-shadow: 0 0 .5rem var(--night-color);
    border-color: var(--night-color);
  }

  .input-container {
    width: 90%;
    display: flex;
  }

  .auth-button {
    position: relative;
    padding: 1rem;
    background-color: var(--night-color);
    border-radius:var(--default-border-radius);
  }

</style>
